### ISSUE TITLE
Entering tunneling mode, even if skipping deepslate block

### ISSUE THREAD

**Issue by catboybinary** [Eli-bassoon/CraftyFunge#1]
IP enters tunneling mode, even thought it is skipped with sea lantern
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/33326440/176675498-fd6ebaec-8f20-4fd3-97be-8b8e03a62a63.gif)

**Comment by Eli-bassoon** [comment]
I have fixed this in v1.0.1.
Thank you for reporting!
